### ISSUE TITLE
cit constraint rules not working

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/generic-dict-schema#6]
the first rule prevents the following rules from being invoked

**Comment by rausch-supola** [comment]
Could this effect the rule in usg
`context="tei:usg[not(@type = 'geographic') and not(@type='socioCultural')]"`
as well?

**Comment by dasch124** [comment]
So, we have several contexts and one element in a document might be matching several rules, right? 

* `tei:cit[not(@type = 'example')]`
* `tei:cit[@type = 'translationEquivalent']`
* `tei:cit[@type = 'translation']`
* `tei:cit[@subtype = 'proverb']`

So we could copy those rules which are now in `tei:cit[not(@type = 'example')]` to the other contexts - however, I feel duplicating the rules clutters the schema and makes it less readable. 

Actually, I think, we have defined the same logic already in the [`<elementSpec>` for `<bibl>`](https://github.com/acdh-oeaw/generic-dict-schema/pull/7/commits/e99c053a58d768b2693a4f3cc833a1801e016aa8#diff-e1508213c32775d146b4fcbf811deb6d25ef840c18753faf18d270f7f29b51d8L533 ) so probably we can remove it in the elementSpec for `<cit>`, couldn't we? For clarity we can leave an XML comment, for example.

**Comment by rausch-supola** [comment]
Actually, I started a pull request which solves the problem. It was a syntax error I guess: https://github.com/acdh-oeaw/generic-dict-schema/pull/7

` <s:rule context="tei:cit/@type[not(. = 'example')]">` instead of
`<s:rule context="tei:cit[not(@type = 'example')]">`

That's why I asked if it concerns the rule in usg as well because it is the same syntax. 

There is no error message or anything, simply the rules are not applied

**Comment by rausch-supola** [comment]
Update:
my solution doesn't seem to work as wished.

While in usg the context MUST be defined as this `context="tei:usg[not(@type = 'geographic') and not(@type='socioCultural')]"`, the first rule in cit `<s:rule context="tei:cit[not(@type = 'example')]">` doesn't seem to work with `<s:rule context="tei:cit/@type[not(. = 'example')]">` either. With the second version the subsequent rules are working, that's the only difference.

**Comment by rausch-supola** [comment]
> Actually, I think, we have defined the same logic already in the [`<elementSpec>` for `<bibl>`](https://github.com/acdh-oeaw/generic-dict-schema/pull/7/commits/e99c053a58d768b2693a4f3cc833a1801e016aa8#diff-e1508213c32775d146b4fcbf811deb6d25ef840c18753faf18d270f7f29b51d8L533) so probably we can remove it in the elementSpec for `<cit>`, couldn't we? For clarity we can leave an XML comment, for example.

I would go for this!

**Comment by rausch-supola** [comment]
I removed the first rule in cit as it is already included in the listBibl rule set (https://github.com/acdh-oeaw/generic-dict-schema/commit/9cfcf7378738c14c20486cb19e2940febdd9ee0f)
